name: Check links

on:
  pull_request:
  schedule:
    - cron: "17 7 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --accept 200,204,206,301,302,307,308,401,403,429
            './**/*.md'
          fail: true
